inherit_from: .rubocop_todo.yml

Layout/SpaceAroundMethodCallOperator:
   Enabled: true

Lint/RaiseException:
   Enabled: true

Lint/StructNewOverride:
   Enabled: true

Style/ExponentialNotation:
   Enabled: true

Style/HashEachMethods:
   Enabled: true

Style/HashTransformKeys:
   Enabled: true

Style/HashTransformValues:
   Enabled: true

# Quite a few matrix operations, so we'll allow "x" and "y" as parameters
Naming/MethodParameterName:
   AllowedNames: ["x", "y"]
